"""The run contract: what every engine may ask of the run it works in, and nothing more.

The engines (objective, synthesis, router, planner, budget, gateway, execution, verifier, performance, replacement,
delivery) are functions of a Run. The orchestrator (engine.Engine) is the only implementation; this protocol is
the boundary between them, so an engine never reaches into another engine's records or the orchestrator's state.
"""
from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable


@runtime_checkable
class Run(Protocol):
    store: object            # the run's event log and records (db.Store)
    registry: object         # the model registry the run is staffed from (registry.Registry)
    intel: object            # the workers' intelligence (intelligence.ModelSource or ScriptedSource)
    paths: dict[str, Path]   # workspaces, integration, main, releases, live, exports
    live_proc: object        # the deployed product's process, if any

    @property
    def cid(self) -> str: ...
    @property
    def meta(self) -> dict: ...
    def set_meta(self, **kw) -> dict: ...

    # the audit trail and the founder's inbox
    def event(self, event_type: str, aggregate_type: str, aggregate_id: str, payload: dict, **kw) -> dict: ...
    def decision(self, kind: str, **kw) -> dict: ...
    def intervention(self, ref: str, what: str) -> None: ...
    def count(self, kind: str) -> int: ...

    # the objective and what it became
    def objective(self) -> dict | None: ...
    def objective_ctx(self) -> dict: ...
    def requirements(self) -> dict | None: ...
    def rules(self) -> list[str]: ...

    # the organization
    def worker(self, wid: str) -> dict | None: ...
    def workers(self) -> list[dict]: ...
    def model_of(self, wid: str) -> str | None: ...
    def persona(self, wid: str) -> str: ...
    def assigner_id(self) -> str | None: ...
    def answerers(self) -> list[str]: ...

    # the work
    def tasks(self) -> list[dict]: ...
    def task(self, tid: str) -> dict: ...
    def save_task(self, t: dict) -> dict: ...
    def workspace(self, wid: str, tid: str) -> Path: ...
    def send(self, kind: str, content: dict | None, routing: dict, task_id: str, sender: str) -> dict: ...
    def gateway(self, worker_id: str, task_id: str, action_type: str, target: str = "", **kw) -> dict: ...
    def escalate(self, t: dict, why: str) -> dict: ...

    # money and intelligence
    def record_call(self, task_id: str, worker: str, purpose: str, usage: dict) -> dict: ...
    def spend(self, worker_id: str, task_id: str, usd: float, layer: str) -> None: ...
